window.PROGRAMACAO = {
  sp: {
    'seg-sex': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'PARADÃO SERTANEJO' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Bom Dia Cidade' },
      { time: '11:00', title: 'Pagodão Da Cidade' },
      { time: '11:30', title: 'Rádio Esportes' },
      { time: '13:00', title: 'Sala de Redação' },
      { time: '15:00', title: 'Chamada Geral' },
      { time: '16:00', title: 'Cidade Não Para' },
      { time: '17:00', title: 'Ponto Final CBN' },
      { time: '19:00', title: 'A VOZ DO BRASIL' },
      { time: '20:00', title: 'Quatro em Campo' },
      { time: '21:00', title: 'Assunto Federal' },
      { time: '22:00', title: 'CBN Noite Total' },
      { time: '23:00', title: 'Love Songs' }
    ],
    'sab': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'Café com Noticia' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Horário Livre 1ª Edição' },
      { time: '10:00', title: 'Horário Livre 2ª Edição' },
      { time: '11:00', title: 'REPÓRTER CBN' },
      { time: '11:03', title: 'Horário Livre 3ª Edição' },
      { time: '11:30', title: 'Rádio Esportes' },
      { time: '13:00', title: 'Itatiaia Agora' },
      { time: '14:00', title: 'Sábado Retrô' },
      { time: '15:00', title: 'CBN Show da Noticia' },
      { time: '21:00', title: 'Noite Livre/JORNADA ESPORTIVA' },
      { time: '23:00', title: 'Love Songs' }
    ],
    'dom': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'Café com Noticia' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Horário Livre 1ª Edição' },
      { time: '10:00', title: 'Horário Livre 2ª Edição' },
      { time: '11:00', title: 'REPÓRTER CBN' },
      { time: '11:03', title: 'Horário Livre 3ª Edição' },
      { time: '12:00', title: 'PARADÃO SERTANEJO' },
      { time: '13:00', title: 'Domingão Esportivo' },
      { time: '15:00', title: 'Futebol Globo CBN/CBN Show da Noticia' },
      { time: '22:00', title: 'Noite Livre' },
      { time: '23:00', title: 'Love Songs' }
    ]
  },
  canoas: {
    'seg-sex': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'PARADÃO SERTANEJO' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Bom Dia Cidade' },
      { time: '11:00', title: 'Pagodão Da Cidade' },
      { time: '11:30', title: 'Rádio Esportes' },
      { time: '13:00', title: 'Sala de Redação' },
      { time: '15:00', title: 'Chamada Geral' },
      { time: '16:00', title: 'Cidade Não Para' },
      { time: '17:00', title: 'Assunto Federal' },
      { time: '18:00', title: 'Cidade Não Para (2ª Parte)' },
      { time: '19:00', title: 'A VOZ DO BRASIL' },
      { time: '20:00', title: 'Jornal da Itatiaia' },
      { time: '20:03', title: 'Conversa de Redação' },
      { time: '20:22', title: 'Jornal da Itatiaia' },
      { time: '21:00', title: 'Conexão Cidade Brasil' },
      { time: '22:00', title: 'Noite Livre' },
      { time: '23:00', title: 'Love Songs' }
    ],
    'sab': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'Café com Noticia' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Horário Livre 1ª Edição' },
      { time: '10:00', title: 'Horário Livre 2ª Edição' },
      { time: '11:00', title: 'REPÓRTER CBN' },
      { time: '11:03', title: 'Horário Livre 3ª Edição' },
      { time: '11:30', title: 'Rádio Esportes' },
      { time: '13:00', title: 'Itatiaia Agora' },
      { time: '14:00', title: 'Sábado Retrô' },
      { time: '16:00', title: 'PARADÃO SERTANEJO' },
      { time: '17:00', title: 'Cidade Não Para/JORNADA ESPORTIVA' },
      { time: '18:00', title: 'Turma do Bate Bola/JORNADA ESPORTIVA' },
      { time: '20:00', title: 'Noite Livre/JORNADA ESPORTIVA' },
      { time: '23:00', title: 'Love Songs' }
    ],
    'dom': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'Café com Noticia' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Horário Livre 1ª Edição' },
      { time: '10:00', title: 'Horário Livre 2ª Edição' },
      { time: '11:00', title: 'REPÓRTER CBN' },
      { time: '11:03', title: 'Horário Livre 3ª Edição' },
      { time: '12:00', title: 'PARADÃO SERTANEJO' },
      { time: '13:00', title: 'Domingão Esportivo' },
      { time: '14:00', title: 'Pré Jornada' },
      { time: '15:30', title: 'Futebol da Gaúcha' },
      { time: '22:00', title: 'Noite Livre' },
      { time: '23:00', title: 'Love Songs' }
    ]
  },
  bh: {
    'seg-sex': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'PARADÃO SERTANEJO' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Bom Dia Cidade' },
      { time: '11:00', title: 'Pagodão Da Cidade' },
      { time: '11:30', title: 'Rádio Esportes' },
      { time: '13:00', title: 'Sala de Redação' },
      { time: '15:00', title: 'Chamada Geral' },
      { time: '16:00', title: 'Cidade Não Para' },
      { time: '17:00', title: 'Assunto Federal' },
      { time: '18:00', title: 'Cidade Não Para (2ª Parte)' },
      { time: '19:00', title: 'A VOZ DO BRASIL' },
      { time: '20:00', title: 'Jornal da Itatiaia' },
      { time: '20:03', title: 'Conversa de Redação' },
      { time: '20:22', title: 'Jornal da Itatiaia' },
      { time: '21:00', title: 'Conexão Cidade Brasil' },
      { time: '22:00', title: 'Noite Livre' },
      { time: '23:00', title: 'Love Songs' }
    ],
    'sab': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'Café com Noticia' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Horário Livre 1ª Edição' },
      { time: '10:00', title: 'Horário Livre 2ª Edição' },
      { time: '11:00', title: 'REPÓRTER CBN' },
      { time: '11:03', title: 'Horário Livre 3ª Edição' },
      { time: '11:30', title: 'Rádio Esportes' },
      { time: '13:00', title: 'Itatiaia Agora' },
      { time: '14:00', title: 'Sábado Retrô' },
      { time: '16:00', title: 'PARADÃO SERTANEJO' },
      { time: '17:00', title: 'Cidade Não Para/JORNADA ESPORTIVA' },
      { time: '18:00', title: 'Turma do Bate Bola/JORNADA ESPORTIVA' },
      { time: '20:00', title: 'Noite Livre/JORNADA ESPORTIVA' },
      { time: '23:00', title: 'Love Songs' }
    ],
    'dom': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'Café com Noticia' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Horário Livre 1ª Edição' },
      { time: '10:00', title: 'Horário Livre 2ª Edição' },
      { time: '11:00', title: 'REPÓRTER CBN' },
      { time: '11:03', title: 'Horário Livre 3ª Edição' },
      { time: '12:00', title: 'PARADÃO SERTANEJO' },
      { time: '13:00', title: 'Domingão Esportivo' },
      { time: '15:00', title: 'Jornada Esportiva' },
      { time: '22:00', title: 'Noite Livre' },
      { time: '23:00', title: 'Love Songs' }
    ]
  },
  pa: {
    'seg-sex': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'PARADÃO SERTANEJO' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Bom Dia Cidade' },
      { time: '11:00', title: 'Pagodão Da Cidade' },
      { time: '11:30', title: 'Rádio Esportes' },
      { time: '13:00', title: 'Sala de Redação' },
      { time: '15:00', title: 'Chamada Geral' },
      { time: '16:00', title: 'Cidade Não Para' },
      { time: '17:00', title: 'Assunto Federal' },
      { time: '18:00', title: 'Cidade Não Para (2ª Parte)' },
      { time: '19:00', title: 'A VOZ DO BRASIL' },
      { time: '20:00', title: 'Jornal da Itatiaia' },
      { time: '20:03', title: 'Conversa de Redação' },
      { time: '20:22', title: 'Jornal da Itatiaia' },
      { time: '21:00', title: 'Conexão Cidade Brasil' },
      { time: '22:00', title: 'Noite Livre' },
      { time: '23:00', title: 'Love Songs' }
    ],
    'sab': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'Café com Noticia' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Horário Livre 1ª Edição' },
      { time: '10:00', title: 'Horário Livre 2ª Edição' },
      { time: '11:00', title: 'REPÓRTER CBN' },
      { time: '11:03', title: 'Horário Livre 3ª Edição' },
      { time: '11:30', title: 'Rádio Esportes' },
      { time: '13:00', title: 'Itatiaia Agora' },
      { time: '14:00', title: 'Sábado Retrô' },
      { time: '16:00', title: 'PARADÃO SERTANEJO' },
      { time: '17:00', title: 'Cidade Não Para/JORNADA ESPORTIVA' },
      { time: '18:00', title: 'Turma do Bate Bola/JORNADA ESPORTIVA' },
      { time: '20:00', title: 'Noite Livre/JORNADA ESPORTIVA' },
      { time: '23:00', title: 'Love Songs' }
    ],
    'dom': [
      { time: '00:00', title: 'Itatiaia é a Dona da Noite' },
      { time: '04:00', title: 'Café com Noticia' },
      { time: '06:00', title: 'Jornal da CBN' },
      { time: '07:00', title: 'Jornal da Itatiaia' },
      { time: '09:00', title: 'Horário Livre 1ª Edição' },
      { time: '10:00', title: 'Horário Livre 2ª Edição' },
      { time: '11:00', title: 'REPÓRTER CBN' },
      { time: '11:03', title: 'Horário Livre 3ª Edição' },
      { time: '12:00', title: 'PARADÃO SERTANEJO' },
      { time: '13:00', title: 'Domingão Esportivo' },
      { time: '15:00', title: 'Jornada Esportiva' },
      { time: '22:00', title: 'Noite Livre' },
      { time: '23:00', title: 'Love Songs' }
    ]
  }
};